### ISSUE TITLE
Wrong QR Render

### ISSUE THREAD

**Issue by elgranshaman** [yoprogramo/QRcode_eSPI#2]
Hello again, 

I am getting the following QR Code which seems quite different from the examples... I am using the eSPI library
![IMG_20211219_144826](https://user-images.githubusercontent.com/44362719/146667845-67543ebd-bb16-40c0-a13e-d4ada5b6338d.jpg)
 
Thanks

**Comment by yoprogramo** [comment]
Hello,

What display model are you using?

**Comment by elgranshaman** [comment]
480*320 ILI9488 4 wire SPI

**Comment by yoprogramo** [comment]
I have just upload a modification to the code, please try with it and if it works I will generate a new version.

**Comment by elgranshaman** [comment]
That fixed it!

**Comment by yoprogramo** [comment]
Thank you for the issue, I'll close now and generate new version.
