### ISSUE TITLE
QR code cannot be read by some applications

### ISSUE THREAD

**Issue by elgranshaman** [yoprogramo/QRcode_eSPI#3]
Hi again we are using your library to generate QR code, and we are trying to read it with our android app (using library Zxing - https://github.com/zxing/zxing).

Unfortunately, we can not read the attached QR code generated by us  (see attachment 1). Also, we tried 6 different apps, and 4 can read it, and 2 cannot, so it seems like we are doing something wrong during generation.

PS: we still can read other ESP QR codes examples from your github page - so it seems like our code might be wrong (?).

I edited your library so I can scale down the size.

```
void QRcode_eSPI::init() {
    //display->init();
    this->screenwidth = display->width();
    this->screenheight = display->height();
    // display->fillScreen(TFT_WHITE);
    int min = screenwidth;
    if (screenheight < screenwidth)
        min = screenheight;
    min = 220;
    multiply = min / WD;
    offsetsX = (screenwidth - (WD * multiply)) / 2;
    offsetsY = (screenheight - (WD * multiply)) / 2;
}
```

Thanks for the help.

![photo_2022-01-26_19-50-35](https://user-images.githubusercontent.com/44362719/151171234-4802fbdb-61f4-410a-bc70-c93df0ee6f93.jpg)

**Comment by yoprogramo** [comment]
Hello @elgranshaman seems your screen have the colors inverted. Usually the QRcodes has to be white background and black dots to be correctly interpreted by readers. If you invert the colors it would be correctly read (as you can see scanning the image).

![inverted](https://user-images.githubusercontent.com/1540921/151184121-4bacf9ae-7156-4307-b221-2c7e45b6adde.png)

You can try to invert it in the library (having into account that you need some white border too) or in the QR reading library instructing it to read inverted codes.

Regards

**Comment by elgranshaman** [comment]
Hello,

Thanks again for your support!

We ended up changing the background to white as we couldn't do an inverted reading on the application.

**Comment by yoprogramo** [comment]
Thanks to you for reporting. I close this issue then.
