### ISSUE TITLE
Compilation error platformio

### ISSUE THREAD

**Issue by kittipon-dev** [yoprogramo/QRcode_eSPI#4]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/25154073/175764968-388dffc1-d762-44e3-b8c3-e39875e3ec66.png">

**Comment by yoprogramo** [comment]
Use version > 2.0.0 in all Qrcode libraries and try again.

**Comment by kittipon-dev** [comment]
> Qrcode libraries and try again.

<img width="942" alt="image" src="https://user-images.githubusercontent.com/25154073/175765729-17cd50fe-96b8-475a-80d3-89da9dc5fe93.png">
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/25154073/175765773-22fb6c02-0173-493a-85ea-06e7061aafbc.png">

**Comment by yoprogramo** [comment]
There are v2.0.0 in the repo use it.

**Comment by kittipon-dev** [comment]
Got it. Thank you very much.

**Comment by yoprogramo** [comment]
Thank you @kittipon-neware,

I have published now in platformio libraries the 2.0.0 version, so you can use it directly from dependencies.
