### ISSUE TITLE
Changing QR code displayed size

### ISSUE THREAD

**Issue by elgranshaman** [yoprogramo/QRcode_eSPI#6]
Hello,

Can you please let me know how can I change the size of the QR code in pixels?

`
void QRcode_eSPI::init() {
    //display->init();
    this->screenwidth = display->width();
    this->screenheight = display->height();
    display->fillScreen(TFT_WHITE);
    int min = screenwidth;
    if (screenheight < screenwidth)
        //min = screenheight;
    min = 220;
    multiply = min / WD;
    offsetsX = (screenwidth - (WD * multiply)) / 2;
    offsetsY = (screenheight - (WD * multiply)) / 2;
}
`

I think it might be by changing `width()` and `height()`

Is there a more elegant way to do it?

Thank you

**Comment by kanslor** [comment]
hello, have you found the elegant way to do?
